const data = {
  products: [
    {
      name: "The Yara Top",
      slug: "the-yara-top",
      description: JSON.stringify([
        "Featuring a textured ribbed stitch pattern in sky blue color with scattered deep-blue accents, it adds a subtle pop of color and detail. The deep V neckline is outlined with a bold blue border, giving it a flattering shape, while the versatile straps can be styled in multiple ways — crisscrossed, tied at the back, or worn straight — for a customizable look.",
      ]),
      price: 20,
      image: "/images/tote.jpg",
      type: "featured",
      category: "Top",
      tags: [
        "Crochet top",
        "handmade top",
        "crochet crop top",
        "summer top",
        "festival wear",
        "boho style top",
        "trendy crochet top",
        "strappy crop top",
        "handmade clothing",
        "Crochet fashion",
      ],
    },
    // {
    //   name: "Crochet Baby Blanket",
    //   slug: "crochet-baby-blanket",
    //   description: "Crochet Ruffle skirt and top set is a feminine and stylish crochet outfit designed to turn heads. The chic crop top pairs perfectly with the matching skirt, which features delicate ruffles at the hem and a subtle slit for a touch of elegance and playfulness.",
    //   price: 90,
    //   image: "/images/ruffle.jpg",
    //   type: "featured",
    //   category: "featured",
    //   tags: ["Crochet set","Handmade crochet outfit","Crochet skirt and top set",
    //     "Crochet matching set","Two-piece crochet outfit","Summer crochet fashion",
    //     "Crochet festival wear","Boho crochet outfit","Crochet ruffle skirt",
    //     "Crochet crop top set","Crochet skirt with slit","Flirty crochet outfit",
    //     "Handmade ruffled set"],
    // },
    {
      name: "crochet rastafarian top and skirt",
      slug: "crochet-rastafarian-top-and-skirt",
      description: JSON.stringify([
        "This vibrant crochet two-piece set features a halter crop top and a fitted mini skirt, designed in bold Rasta-inspired stripes of green, red, and yellow. Handcrafted with care, the set combines comfort, style, and culture—perfect for festivals, beach days, or making a statement wherever you go",
      ]),
      price: 60,
      image: "/images/granny.jpg",
      type: "pattern",
      category: "Patterns",
      tags: [
        "Crochet",
        "crochet top",
        "rastafarian",
        "crochet skirt",
        "Ascarcrochets",
      ],
    },
    {
      name: "crochet rastafarian top and skirt (Ready to Wear)",
      slug: "crochet-rastafarian-top-and-skirt-readytowear",
      description: JSON.stringify([
        "This vibrant crochet two-piece set features a halter crop top and a fitted mini skirt, designed in bold Rasta-inspired stripes of green, red, and yellow. Handcrafted with care, the set combines comfort, style, and culture—perfect for festivals, beach days, or making a statement wherever you go",
      ]),
      price: 60,
      image: "/images/granny.jpg",
      type: "readytowear",
      category: "readytowear",
      tags: [
        "Crochet",
        "crochet top",
        "rastafarian",
        "crochet skirt",
        "Ascarcrochets",
      ],
    },
    {
      name: "Amigurumi Bunny Pattern",
      slug: "amigurumi-bunny-pattern",
      description: JSON.stringify(["Cute crochet bunny doll pattern"]),
      price: 6,
      image: "/images/bunny.jpg",
      type: "pattern",
      category: "Patterns",
      tags: ["amigurumi", "crochet bunny", "doll pattern"],
    },
    // {
    //   name: "Crochet Maxi Skirt",
    //   slug: "crochet-maxi-skirt",
    //   description: "Beautiful handmade crochet maxi skirt with slit",
    //   price: 75,
    //   image: "/images/skirt.jpg",
    //   type: "readytowear",
    //   category: "Clothing",
    //   tags: [
    //     "c2c crochet skirt",
    //     "c2c crochet stitch",
    //     "crochet beach skirt",
    //     "crochet designs",
    //     "crochet maxi skirt",
    //     "crochet skirt",
    //     "crochet skirt pattern",
    //     "crochet skirt with a slit",
    //     "crochet striped skirt",
    //     "crochet summer wear",
    //     "diy skirt",
    //     "shylercrochets",
    //     "shylercrochets designs",
    //   ],
    // },
    {
      name: "crochet ruffle skirt and top",
      slug: "crochet-ruffle-skirt-and-top",
      description: JSON.stringify([
        "Crochet Ruffle skirt and top set is a feminine and stylish crochet outfit designed to turn heads. The chic crop top pairs perfectly with the matching skirt,which features delicate ruffles at the hem and a subtle slit for a touch of elegance and playfulness",
        "Handmade with love, Mira is lightweight, breathable, and versatile — ideal for summer days, vacations, beach outings, or special events. Wear the pieces together for a statement look, or mix and match with your wardrobe favorites.",
      ]),
      price: 90,
      image: "/images/ruffle2.jpg",
      type: "featured",
      category: "Clothing",
      tags: [
        "Crochet set",
        "Handmade crochet outfit",
        "Crochet skirt and top set",
        "Crochet matching set",
        "Two-piece crochet outfit",
        "Summer crochet fashion",
        "Crochet festival wear",
        "Boho crochet outfit",
        "Crochet ruffle skirt",
        "Crochet crop top set",
        "Crochet skirt with slit",
        "Flirty crochet outfit",
        "Handmade ruffled set",
      ],
    },
    {
      name: "crochet ruffle skirt and top(Ready to Wear)",
      slug: "crochet-ruffle-skirt-and-top-readytowear",
      description: JSON.stringify([
        "Crochet Ruffle skirt and top set is a feminine and stylish crochet outfit designed to turn heads. The chic crop top pairs perfectly with the matching skirt,which features delicate ruffles at the hem and a subtle slit for a touch of elegance and playfulness",
        "Handmade with love, Mira is lightweight, breathable, and versatile — ideal for summer days, vacations, beach outings, or special events. Wear the pieces together for a statement look, or mix and match with your wardrobe favorites.",
      ]),
      price: 90,
      image: "/images/ruffle2.jpg",
      type: "readytowear",
      category: "Clothing",
      tags: [
        "Crochet set",
        "Handmade crochet outfit",
        "Crochet skirt and top set",
        "Crochet matching set",
        "Two-piece crochet outfit",
        "Summer crochet fashion",
        "Crochet festival wear",
        "Boho crochet outfit",
        "Crochet ruffle skirt",
        "Crochet crop top set",
        "Crochet skirt with slit",
        "Flirty crochet outfit",
        "Handmade ruffled set",
      ],
    },
  ],
};

export default data;
